name: gh-refs-deps
on: [push]
jobs:
  gh-actions-refs:
    runs-on: ubuntu-latest
    steps:
      - name: JS actions
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Sunil
