name: multiple-jobs-test

on: [push]

jobs:
  multiple-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "this is from multiple job using "

      - name: step2
        run:  |
          echo "this is for multiple job1"
          echo "helllooooo"
          eco "this will be failed"
