name: sample-gh-actions
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "this is step1"

      - name: step2
        run: echo "this is step2"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2-step1
        run: echo "job2-step1"
